export * from './createInmueble';
export * from './updateInmueble';
export * from './getListaInmuebles';
export * from './getInmubleById';
export * from './deleteInmuebleById';
export * from './getMunicipios';
export * from './getProvincias';
export * from './getListaClientes';
export * from './login';